Iter18
denis-oreshkevich/shortener pull request #20
Opened 2023-12-25 22:08 UTC by denis-oreshkevich

2023-12-27 09:41 UTC, gonozov0 requested changes
Отличная работа 👍
Внес много улучшений, особенно в плане документации и работе с миграциями
Оставил буквально один комментарий по коду.
Так же подскажи плиз, удалось ли разобраться с pprof? Снять загрузку в рантайме и посмотреть визуально, какие части твоего кода дольше всего выполняются или занимают памяти.
Спрашиваю потому, что пообщавшись на 1:1 у многих не сложилось полное понимание, как он работает
https://app.pachca.com/chats?thread_id=2568500&sidebar_message=112734394

2023-12-27 09:41 UTC, gonozov0 commented on internal/app/storage/dbstorage.go
> +	db, err := sql.Open("pgx", dsn)
Почему тут не используешь свою новую функцию initDatasource?

2023-12-27 10:54 UTC, denis-oreshkevich commented on internal/app/storage/dbstorage.go
> +	db, err := sql.Open("pgx", dsn)
Прямо чтобы до конца разобрался с pprof - не могу такого сказать. Вроде как понял принцип, получилось увидеть свои методы. Записался к вам на 1-1 на 5 января - планирую задавать вопросы по этой теме в том числе.

2023-12-28 09:00 UTC, gonozov0 commented on internal/app/storage/dbstorage.go
> +	db, err := sql.Open("pgx", dsn)
Ага, отлично, тогда там обсудим

2023-12-28 09:01 UTC, gonozov0 approved these changes
Работа принята 👍
Все моменты поправлены

2024-01-02 17:42 UTC, merged