Iter23
denis-oreshkevich/shortener pull request #25
Opened 2024-01-29 08:52 UTC by denis-oreshkevich

2024-01-30 08:33 UTC, gonozov0 requested changes
Отличная работа 👍
Особенно лаконично получилась доработка конфига
Оставил пару комментариев по улучшению кода

2024-01-30 08:33 UTC, gonozov0 commented on cmd/shortener/main.go
> +	signal.Notify(sigint, syscall.SIGTERM, syscall.SIGINT, syscall.SIGQUIT)
Используй лучше NotifyContext, с ним удобней работать, т.к. можно передать в требующие контекст функции и методы, которые также graceful отработают при этих сигналах

2024-01-30 08:33 UTC, gonozov0 commented on cmd/shortener/main.go
> +		manager, errHTTPS := server.NewCertManager("./certs/cert.pem", "./certs/key.pem")
Сертификат генерируешь на 10 лет, но при этом пересоздаешь при каждом запуске. Давай добавим проверку, что сертификат уже существует

2024-01-30 08:33 UTC, gonozov0 commented on cmd/shortener/main.go
> +	wg.Add(1)
А у тебя больше нет никаких горутин в проекте, которые также надо дожидаться?

2024-01-30 15:11 UTC, denis-oreshkevich commented on cmd/shortener/main.go
> +		manager, errHTTPS := server.NewCertManager("./certs/cert.pem", "./certs/key.pem")
Добавил проверку внутрь server.NewCertManager

2024-01-30 15:12 UTC, denis-oreshkevich commented on cmd/shortener/main.go
> +	wg.Add(1)
Если и есть, то наверное я не понимаю какие.

2024-01-31 13:37 UTC, gonozov0 approved these changes
Работа принята 👍
Все моменты поправлены

2024-02-01 10:40 UTC, merged